version: "3.8"

services:

  cli:
    build:
      context: .
      dockerfile: Dockerfile-cli
    environment:
      DEBUG: dev

  apache:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile-apache
      tags:
        - "ghcr.io/chrecht/php:8.2-apache"
        - "ghcr.io/chrecht/php:8.2.4-apache"
    environment:
      DEBUG: dev
    ports:
      - "1180:80"
    volumes:
      - ./test/html:/var/www/html

  fpm:
    build:
      context: .
      dockerfile: Dockerfile-fpm
    environment:
      DEBUG: dev
    ports:
      - "9000:9000"
    volumes:
      - ./test/html:/var/www/html
