FROM php:8.2.4-apache-bullseye
LABEL maintainer="Christian WALDBILLIG <christian@waldbillig.io>"

ENV TERM="xterm" \
    LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    ACCEPT_EULA="Y" \
    APACHE_RUN_USER="site" \
    APACHE_RUN_GROUP="site"

ARG DEBIAN_FRONTEND=noninteractive


#####################
# Add User site
#####################
RUN addgroup --gid 667 site \
 && adduser --disabled-password --gecos '' --home /var/www --shell "/sbin/nologin" --uid 667 --gid 667 site \
 && mkdir -p /var/www/html \
 && chown site.site -R /var/www

#####################
# Requirements
#####################
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    zlib1g-dev \
    libz-dev \
    libzip-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libssl-dev \
    libxml2-dev \
    zlib1g-dev \
    libicu-dev \
    libssh2-1-dev \
    g++ \
    apt-transport-https \
    ca-certificates \
    locales \
    locales-all \
    msmtp \
    zip \
    unzip \
    nano \
    vim \
    git \
    apt-utils \
    gnupg \
    libcap2-bin \
    procps \
    gnupg2 \
    libzip-dev \
    zip \
    unzip \
    libonig-dev \
    libxslt-dev \
    libbz2-dev \
  && rm -rf /var/lib/apt/lists/*


#####################################
# FFMPEG & MediaInfo
#####################################
RUN curl -O https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb \
    && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb \
    && echo "deb http://www.deb-multimedia.org bullseye main non-free" >> /etc/apt/sources.list \
    && echo "deb http://www.deb-multimedia.org bullseye-backports main" >> /etc/apt/sources.list \
    && apt-get update && apt-get install -y zip unzip wget imagemagick --no-install-recommends \
    && apt-get install -t bullseye-backports -y ffmpeg mediainfo \
    && rm -r /var/lib/apt/lists/*

#####################################
# MS ODBC Driver for SQL Server
#####################################
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && echo "Package: unixodbc\nPin: origin \"packages.microsoft.com\"\nPin-Priority: 100\n" >> /etc/apt/preferences.d/microsoft \
    && echo "Package: unixodbc-dev\nPin: origin \"packages.microsoft.com\"\nPin-Priority: 100\n" >> /etc/apt/preferences.d/microsoft \
    && echo "Package: libodbc1:amd64\nPin: origin \"packages.microsoft.com\"\nPin-Priority: 100\n" >> /etc/apt/preferences.d/microsoft \
    && echo "Package: odbcinst\nPin: origin \"packages.microsoft.com\"\nPin-Priority: 100\n" >> /etc/apt/preferences.d/microsoft \
    && echo "Package: odbcinst1debian2:amd64\nPin: origin \"packages.microsoft.com\"\nPin-Priority: 100\n" >> /etc/apt/preferences.d/microsoft \
    && apt-get update \
    && apt-get install -y msodbcsql18 mssql-tools18 unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*


RUN docker-php-ext-install -j$(nproc) \
        mbstring \
        exif \
        pcntl \
        bcmath \
        gd \
        xsl \
        bz2 \
        mysqli \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        intl \
        sockets \
        opcache \
        soap \
        zip \
    && pecl channel-update pecl.php.net \
    && pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable \
        sqlsrv \
        pdo_sqlsrv \
        bz2 \
        pdo_mysql \
        pdo_pgsql \
        intl \
        sockets \
        opcache \
        soap

RUN mkdir -p /usr/src/php/ext \
    && cd /usr/src/php/ext \
    && pecl bundle redis \
    && docker-php-ext-configure redis \
    && docker-php-ext-install -j$(nproc) redis \
    && rm -rf /usr/src/php/ext

COPY scripts /scripts
COPY php/conf.d/* /usr/local/etc/php/conf.d/
COPY apache2/mods-enabled/* /etc/apache2/mods-enabled/
COPY apache2/conf-enabled/* /etc/apache2/conf-enabled/
COPY apache2/sites-enabled/* /etc/apache2/sites-enabled/

RUN a2enmod remoteip

USER site
