image: docker:stable

services:
  - name: docker:dind
    alias: dockerdaemon

stages: 
  - build

variables:
  DOCKER_HOST: tcp://dockerdaemon:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --platform=linux/amd64 --pull -t $CONTAINER_TEST_IMAGE -f ./php/8.2/Dockerfile-apache ./php/8.2
    - docker push $CONTAINER_TEST_IMAGE
