image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages: 
  - build

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --platform=linux/amd64 --pull -t $CONTAINER_TEST_IMAGE ./php/8.2/Dockerfile-apache
    - docker push $CONTAINER_TEST_IMAGE
