stages:
  - build

variables:
  FOO: bar

build-8.2-apache:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  variables:
    VARIANT: apache
  script:
    - source ${CI_PROJECT_DIR}/php/8.2/.env
    - echo ${MAJOR}.${MINOR}.${PATCH}-${VARIANT}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR.$PATCH-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"

build-8.2-cli:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  variables:
    VARIANT: cli
  script:
    - source ${CI_PROJECT_DIR}/php/8.2/.env
    - echo ${MAJOR}.${MINOR}.${PATCH}-${VARIANT}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR.$PATCH-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"


build-8.2-fpm:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  variables:
    VARIANT: fpm
  script:
    - source ${CI_PROJECT_DIR}/php/8.2/.env
    - echo ${MAJOR}.${MINOR}.${PATCH}-${VARIANT}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR.$PATCH-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"
