image: docker:stable

services:
  - name: docker:dind
    alias: dockerdaemon

stages: 
  - test

variables:
  DOCKER_HOST: tcp://dockerdaemon:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# before_script:
#   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# build-8.2:
#   stage: build
#   script:
#     - "[ -f ./php/8.2/.version_major ] && export MAJOR=$(cat ./php/8.2/.version_major)"
#     - "[ -f ./php/8.2/.version_minor ] && export MINOR=$(cat ./php/8.2/.version_minor)"
#     - "[ -f ./php/8.2/.version_variant ] && export VARIANT=$(cat ./php/8.2/.version_variant)"
#     - |
#         docker build --platform=linux/amd64 --pull \
#           -t $CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT \
#           -t $CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT \
#           -f ./php/8.2/Dockerfile-apache ./php/8.2
#     - docker push $CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT
#     - docker push $CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT

test:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl config get-contexts
    - kubectl config use-context containers/docker-library:elastic-observability01
    - kubectl get pods -A
