stages:
  - build

variables:
  FOO: bar

scheduled-docker-build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: 
    name: debian:bullseye-slim
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl ca-certificates git
    - ./check-version-and-create-tag.sh


build-8.2-apache:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    VARIANT: apache
  script:
    - source ${CI_PROJECT_DIR}/php/8.2/.env
    - echo ${MAJOR}.${MINOR}.${PATCH}-${VARIANT}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR.$PATCH-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"

build-8.2-cli:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    VARIANT: cli
  script:
    - source ${CI_PROJECT_DIR}/php/8.2/.env
    - echo ${MAJOR}.${MINOR}.${PATCH}-${VARIANT}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR.$PATCH-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"


build-8.2-fpm:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    VARIANT: fpm
  script:
    - source ${CI_PROJECT_DIR}/php/8.2/.env
    - echo ${MAJOR}.${MINOR}.${PATCH}-${VARIANT}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR.$PATCH-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"
