image: 
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

services:
  - name: kaniko

stages: 
  - build

variables:
  FOO: bar

before_script:
  - apk --update add curl jq git bash
  - |
    export MAJOR=$(curl --silent https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages | grep "Package: php8.2-cli$" -A 5 | grep Version | sed -En  's/^Version: ([0-9]+\.[0-9]+).*/\1/p')
    export MINOR=$(curl --silent https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages | grep "Package: php8.2-cli$" -A 5 | grep Version | sed -En  's/^Version: [0-9]+\.[0-9]+\.([0-9]+).*/\1/p')
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# scheduled-docker-build:
#   stage: build
#   rules:
#     - if: '$CI_COMMIT_TAG == null'
#   script:
#     - ./check-version-and-create-tag.sh
# #  rules:
# #    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED


build-8.2-apache:
  stage: build
  # rules:
  #   - if: $CI_COMMIT_TAG
  variables:
    VARIANT: apache
  script:
    - |
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/php/8.2/$VARIANT"
      --dockerfile "${CI_PROJECT_DIR}/php/8.2/$VARIANT/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT"
      --destination "$CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT"

# build-8.2-cli:
#   stage: build
#   variables:
#     VARIANT: cli
#   script:
#     - |
#         docker build --platform=linux/amd64 --pull \
#           -t $CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT \
#           -t $CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT \
#           -f ./php/8.2/$VARIANT/Dockerfile ./php/8.2/$VARIANT
#     - docker push $CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT
#     - docker push $CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT

# build-8.2-fpm:
#   stage: build
#   variables:
#     VARIANT: fpm
#   script:
#     - |
#         docker build --platform=linux/amd64 --pull \
#           -t $CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT \
#           -t $CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT \
#           -f ./php/8.2/$VARIANT/Dockerfile ./php/8.2/$VARIANT
#     - docker push $CI_REGISTRY_IMAGE/php:$MAJOR.$MINOR-$VARIANT
#     - docker push $CI_REGISTRY_IMAGE/php:$MAJOR-$VARIANT

# # test:
# #   stage: test
# #   image:
# #     name: bitnami/kubectl:latest
# #     entrypoint: [""]
# #   script:
# #     - kubectl config use-context $KUBE_CONTEXT
# #     - kubectl get pods -A
# #     - kubectl get nodes -o wide

