FROM nginx:1.24-bullseye
LABEL maintainer="Christian WALDBILLIG <christian@waldbillig.io>"
LABEL org.opencontainers.image.source="https://github.com/chrecht/docker-library"

COPY nginx.conf /etc/nginx/nginx.conf
