
run-apache:
	docker compose build --pull apache
	docker compose up apache

run-cli:
	docker compose build --pull cli
	docker compose up cli


run-fpm:
	docker compose build --pull fpm
	docker compose up fpm
