name: PHP 8.3

on:
  push:
    tags:
      - "v8.3.*"
  workflow_dispatch:

env:
  PHP_MAJOR_VERSION: 8.3

jobs:

  docker-apache:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          latest=$(curl --silent https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages | grep "Package: libapache2-mod-php${PHP_MAJOR_VERSION}$" -A 5 | grep Version | sed -En  's/^Version: ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')
          ver_major=$(echo $latest | sed -En 's/^([0-9]+)\.[0-9]+\.[0-9]+/\1/p')
          ver_minor=$(echo $latest | sed -En 's/^[0-9]+\.([0-9]+)\.[0-9]+/\1/p')
          ver_patch=$(echo $latest | sed -En 's/^[0-9]+\.[0-9]+\.([0-9]+)/\1/p')

          echo "VERSION=$latest" >> $GITHUB_OUTPUT
          echo "MAJOR=$ver_major" >> $GITHUB_OUTPUT
          echo "MINOR=$ver_minor" >> $GITHUB_OUTPUT
          echo "PATCH=$ver_patch" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/chrecht/docker-library/php
          tags: |
            type=raw,value=${{ steps.get_version.outputs.VERSION }}-apache
            type=raw,value=${{ steps.get_version.outputs.MAJOR }}.${{ steps.get_version.outputs.MINOR }}-apache
          flavor: |
            latest=false

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./php/${{ env.PHP_MAJOR_VERSION }}/apache
          file: ./php/${{ env.PHP_MAJOR_VERSION }}/apache/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-cli:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          latest=$(curl --silent https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages | grep "Package: php${PHP_MAJOR_VERSION}-cli$" -A 5 | grep Version | sed -En  's/^Version: ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')
          ver_major=$(echo $latest | sed -En 's/^([0-9]+)\.[0-9]+\.[0-9]+/\1/p')
          ver_minor=$(echo $latest | sed -En 's/^[0-9]+\.([0-9]+)\.[0-9]+/\1/p')
          ver_patch=$(echo $latest | sed -En 's/^[0-9]+\.[0-9]+\.([0-9]+)/\1/p')

          echo "VERSION=$latest" >> $GITHUB_OUTPUT
          echo "MAJOR=$ver_major" >> $GITHUB_OUTPUT
          echo "MINOR=$ver_minor" >> $GITHUB_OUTPUT
          echo "PATCH=$ver_patch" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/chrecht/docker-library/php
          tags: |
            type=raw,value=${{ steps.get_version.outputs.VERSION }}-cli
            type=raw,value=${{ steps.get_version.outputs.MAJOR }}.${{ steps.get_version.outputs.MINOR }}-cli
          flavor: |
            latest=false

      - name: Login to image repository
        #if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./php/${{ env.PHP_MAJOR_VERSION }}/cli
          file: ./php/${{ env.PHP_MAJOR_VERSION }}/cli/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-fpm:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          latest=$(curl --silent https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages | grep "Package: php${PHP_MAJOR_VERSION}-fpm$" -A 5 | grep Version | sed -En  's/^Version: ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')
          ver_major=$(echo $latest | sed -En 's/^([0-9]+)\.[0-9]+\.[0-9]+/\1/p')
          ver_minor=$(echo $latest | sed -En 's/^[0-9]+\.([0-9]+)\.[0-9]+/\1/p')
          ver_patch=$(echo $latest | sed -En 's/^[0-9]+\.[0-9]+\.([0-9]+)/\1/p')

          echo "VERSION=$latest" >> $GITHUB_OUTPUT
          echo "MAJOR=$ver_major" >> $GITHUB_OUTPUT
          echo "MINOR=$ver_minor" >> $GITHUB_OUTPUT
          echo "PATCH=$ver_patch" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/chrecht/docker-library/php
          tags: |
            type=raw,value=${{ steps.get_version.outputs.VERSION }}-fpm
            type=raw,value=${{ steps.get_version.outputs.MAJOR }}.${{ steps.get_version.outputs.MINOR }}-fpm
          flavor: |
            latest=false

      - name: Login to image repository
        #if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./php/${{ env.PHP_MAJOR_VERSION }}/fpm
          file: ./php/${{ env.PHP_MAJOR_VERSION }}/fpm/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
