name: Build & Push

on:
  push:
    tags:
      - "v*"
  # pull_request:
  #   branches:
  #     - "main"

jobs:

  docker-cli:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/chrecht/docker-library/php
          tags: |
            type=semver,pattern={{version}},suffix=-cli,latest=false

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./php/8.2/cli
          file: ./php/8.2/cli/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
